export { default as Businesses } from './Businesses'
export { default as Promotions } from './Promotions'
export { default as Home } from './Home'
export { default as Cars } from './Cars'
export { default as Clothes } from './Clothes'
export { default as Smartphones } from './Smartphones'
export { default as Market } from './Market'